#!/usr/bin/env just --justfile

leaks:
    cargo build
    leaks -atExit -- target/debug/leaks_test

bench:
    cargo build
    time target/debug/leaks_test

macosx64:
    cargo build --release --target x86_64-apple-darwin

macosarm64:
    cargo build --release --target aarch64-apple-darwin

macos: macosx64 macosarm64
    [ -d target/universal-apple-darwin/release ] || mkdir -p target/universal-apple-darwin/release
    lipo -create -output target/universal-apple-darwin/release/libkommand_core.a \
        target/x86_64-apple-darwin/release/libkommand_core.a \
        target/aarch64-apple-darwin/release/libkommand_core.a

linuxx64:
    CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=x86_64-unknown-linux-gnu-gcc \
    cargo build --release --target x86_64-unknown-linux-gnu

linuxarm64:
    CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-unknown-linux-gnu-gcc \
    cargo build --release --target aarch64-unknown-linux-gnu

linux: linuxx64 linuxarm64

winx64:
    cargo build --release --target x86_64-pc-windows-gnu

xwinx64:
    CARGO_TARGET_X86_64_PC_WINDOWS_GNU_LINKER=/Users/bppleman/.konan/dependencies/apple-llvm-20200714-macos-x64-essentials/bin/clang++ \
    rustup run nightly cargo xbuild -Zbuild-std --release --target x86_64-pc-windows-gnu

win: winx64

all: macos linux win
